ALPHABET = {
    "a": {
        "pose": "fist_thumb_side",
        "desc": "Punho fechado, polegar ao lado do indicador",
        "duration": 0.8,
        "movement": False,
    },
    "b": {
        "pose": "flat_palm",
        "desc": "Quatro dedos estendidos juntos, polegar dobrado",
        "duration": 0.8,
        "movement": False,
    },
    "c": {
        "pose": "c_curve",
        "desc": "Dedos curvados formando letra C",
        "duration": 0.8,
        "movement": False,
    },
    "d": {
        "pose": "index_up_circle",
        "desc": "Indicador pra cima, demais formam circulo",
        "duration": 0.8,
        "movement": False,
    },
    "e": {
        "pose": "claw_closed",
        "desc": "Dedos dobrados nas juncoes, polegar pra dentro",
        "duration": 0.8,
        "movement": False,
    },
    "f": {
        "pose": "ok_outside",
        "desc": "Polegar e indicador circulo por fora, 3 dedos estendidos",
        "duration": 0.8,
        "movement": False,
    },
    "g": {
        "pose": "pinch_up",
        "desc": "Indicador e polegar apontando pra cima, paralelos",
        "duration": 0.8,
        "movement": False,
    },
    "h": {
        "pose": "two_fingers_horizontal",
        "desc": "Indicador e medio horizontal, polegar entre eles + rotacao",
        "duration": 1.2,
        "movement": True,
        "movement_type": "rotation",
    },
    "i": {
        "pose": "pinky_up",
        "desc": "Punho fechado, mindinho estendido pra cima",
        "duration": 0.8,
        "movement": False,
    },
    "j": {
        "pose": "pinky_hook",
        "desc": "Mindinho desenha letra J no ar",
        "duration": 1.2,
        "movement": True,
        "movement_type": "trace_j",
    },
    "k": {
        "pose": "two_fingers_up",
        "desc": "Indicador e medio com polegar entre eles + movimento pra cima",
        "duration": 1.2,
        "movement": True,
        "movement_type": "upward",
    },
    "l": {
        "pose": "l_shape",
        "desc": "Polegar e indicador em angulo reto (L)",
        "duration": 0.8,
        "movement": False,
    },
    "m": {
        "pose": "three_over_thumb",
        "desc": "Tres dedos sobre polegar dobrado",
        "duration": 0.8,
        "movement": False,
    },
    "n": {
        "pose": "two_over_thumb",
        "desc": "Dois dedos sobre polegar dobrado",
        "duration": 0.8,
        "movement": False,
    },
    "o": {
        "pose": "circle",
        "desc": "Todos os dedos curvados tocando polegar, formando O",
        "duration": 0.8,
        "movement": False,
    },
    "p": {
        "pose": "two_fingers_down",
        "desc": "Mesma forma de H/K mas apontando pra baixo, estatico",
        "duration": 0.8,
        "movement": False,
    },
    "q": {
        "pose": "pinch_down",
        "desc": "Polegar e indicador apontando pra baixo",
        "duration": 0.8,
        "movement": False,
    },
    "r": {
        "pose": "crossed_fingers",
        "desc": "Indicador e medio cruzados",
        "duration": 0.8,
        "movement": False,
    },
    "s": {
        "pose": "fist_thumb_front",
        "desc": "Punho fechado, polegar sobre os dedos",
        "duration": 0.8,
        "movement": False,
    },
    "t": {
        "pose": "thumb_inside",
        "desc": "Polegar entre indicador e medio (por dentro)",
        "duration": 0.8,
        "movement": False,
    },
    "u": {
        "pose": "two_fingers_together",
        "desc": "Indicador e medio estendidos juntos pra cima",
        "duration": 0.8,
        "movement": False,
    },
    "v": {
        "pose": "v_shape",
        "desc": "Indicador e medio em V, separados",
        "duration": 0.8,
        "movement": False,
    },
    "w": {
        "pose": "three_fingers_spread",
        "desc": "Indicador, medio e anelar estendidos separados",
        "duration": 0.8,
        "movement": False,
    },
    "x": {
        "pose": "hook_index",
        "desc": "Indicador em gancho, puxando em direcao ao corpo",
        "duration": 1.2,
        "movement": True,
        "movement_type": "pull_hook",
    },
    "y": {
        "pose": "shaka",
        "desc": "Polegar e mindinho estendidos, 3 dedos fechados",
        "duration": 0.8,
        "movement": False,
    },
    "z": {
        "pose": "index_trace",
        "desc": "Indicador desenha letra Z no ar",
        "duration": 1.2,
        "movement": True,
        "movement_type": "trace_z",
    },
}
